### ISSUE TITLE
Crash on Unrecognized Certificate Extension

### ISSUE THREAD

**Issue by TwelveBaud** [janpieterz/seq-input-certificatecheck#3]
If a certificate includes an extension that isn't recognized by .NET, the `X509Extension.Oid.FriendlyName` field is null. While trying to [get the list of SANs](https://github.com/janpieterz/seq-input-certificatecheck/blob/a7ad81e361a71be18be87afa98e7f2e11e74ceb2/Seq.Input.CertificateCheck/Extensions/Certificate2Extensions.cs#L17), if one of these extensions is encountered first, a `NullReferenceException` is thrown. There's an attempt to catch this when [initially checking the certificate](https://github.com/janpieterz/seq-input-certificatecheck/blob/a7ad81e361a71be18be87afa98e7f2e11e74ceb2/Seq.Input.CertificateCheck/CertificateValidityCheck.cs#L30), but because of the LINQ query, it isn't reified until the reporter [tries to serialize it](https://github.com/janpieterz/seq-input-certificatecheck/blob/a7ad81e361a71be18be87afa98e7f2e11e74ceb2/Seq.Input.CertificateCheck/CertificateCheckReporter.cs#L24), and the exception is actually thrown at that point, resulting in the check not being logged (and an ["unhandled exception" log](https://github.com/janpieterz/seq-input-certificatecheck/blob/a7ad81e361a71be18be87afa98e7f2e11e74ceb2/Seq.Input.CertificateCheck/CertificateCheckTask.cs#L48) in its place).

**Comment by janpieterz** [comment]
Ah yes, that slipped through. Would you be able to add a PR with a fix and a small test for it @TwelveBaud ?

**Comment by TwelveBaud** [comment]
I don't think I have a way to self-host a test for it -- one of the endpoints it was checking was localhost and had been misassigned a cert with `1.3.6.1.4.1.311.84.1.1`, which [ASP.NET Core uses for development certs](https://github.com/dotnet/aspnetcore/blob/main/src/Shared/CertificateGeneration/CertificateManager.cs), but you'd never see one of those in the wild -- but PRs for the fix and an improved smoke tester will be up shortly.
